In [ ]:
def power(a,b):
    
    # ** What is 7 to the power of 4?**
    
    return (a**b)


In [ ]:
out= power(7,4)
print(out)

2401


In [ ]:
def split_str(s):
    
    # ** Split this string:**
     
#     s = "Hi there Sam!"
     
# **into a list. **

    return list(s.split())

In [ ]:
s1= split_str( "Hi there Sam!")
print(s1)

['Hi', 'there', 'Sam!']


In [ ]:
def format(planet,diameter):
  return ("The diameter of {} is {} kilometers".format(planet,diameter))

In [ ]:
planet="earth"
diameter = 12742
print(format(planet,diameter))


The diameter of earth is 12742 kilometers


In [ ]:
def indexing(lst):

# ** Given this nested list, use indexing to grab the word "hello" **
# solution:
  return lst[3][1][2][0]
 

In [ ]:
lst= [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(indexing(lst))




hello


In [ ]:
def dictionary(d):                                                                               
# ** Given this nested dictionary grab the word "hello". Be prepared, this will be annoying/tricky **

 
 # solution :
 return d['k1'][3]['tricky'][3]['target'][3]


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(dictionary(d))

hello


In [ ]:
def subjective():

# ** What is the main difference between a tuple and a list? **
# Tuple is immutable 
#whereas list are mutable meaning the items can be changed 

    return None

In [ ]:
def domainGet(email):
    
    # ** Create a function that grabs the email website domain from a string in the form: **
# 
#     user@domain.com
#     
# **So for example, passing "user@domain.com" would return: domain.com**
  k = email.index("@")
  return email[k+1:]
  



In [ ]:
s = 'user@domain.com'
print(domainGet(s))

domain.com


In [ ]:
#or another method 
def DomainGet(email):

   
  return  email.split("@")[1]

In [ ]:
e = "user@domain.com"
print(DomainGet(e))

domain.com


In [ ]:

def findDog(st):
    
# ** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **
  
  if("dog" in st):
    return True
  else:
    return False

      
    
  
  
     

In [ ]:
findDog("this is cute dog")

True

In [ ]:


def countDog(st):

  return(len(list(filter(lambda item: item == "dog" , st.split()))))
      
    # ** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **
        

       


In [ ]:
st = " the  dog car is dog cool  is the full dog"
print(countDog(st))

3


In [ ]:
# Another method 
#for Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases
def CountDog(pt):
      m=0
      for i in range(len(pt)):
    # ** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **
         if (pt[i] == 'd'and pt [i+1]== 'o'and pt [i+2]=='g'):
          m+=1
      return m


In [ ]:
pt = "this is   a cute dog, i love this dog "
print(CountDog(pt))

2


In [ ]:
def lambdafunc(seq):
    
    # ** Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. For example:**
# 
#     seq = ['soup','dog','salad','cat','great']
  l =list(filter(lambda item: item[0] == "s",seq))
  return (l)
# **should be filtered down to:**
# 
#     ['soup','salad']
 

In [ ]:
seq = ['soup','dog','salad','cat','great']
print(lambdafunc(seq))

['soup', 'salad']


In [ ]:
def caught_speeding(speed, is_birthday):
  if(is_birthday==True):
        i = 5

  else:
        i = 0

  if(speed<=60+i):
        return "No Ticket"

  elif(speed>=61+i and speed<=80+i):
        return "Small Ticket"

  elif(speed>=81+i):
        return "Big Ticket"

In [ ]:
#example
print(caught_speeding(62, True))

No Ticket


# numpy part


In [155]:
!pip install numpy
import numpy as np


In [141]:
def create_arr_of_fives():

  #### Create an array of 10 fives
  #### Convert your output into list 
  arr = np.array([5,5,5,5,5,5,5,5,5,5])
  #### e.g return list(arr) 

  return list(arr)

In [143]:
print(create_arr_of_fives())

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [163]:
def even_num(p):

  ### Create an array of all the even integers from 10 to 50
  ### Convert your output into list 
  ### e.g return list(arr) 
  p= (np.arange(10,51))
  arr= filter(lambda item: item%2 == 0,p)
  return list(arr)




In [165]:

print( even_num(p))

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [168]:
def create_matrix():

  ### Create a 3x3 matrix with values ranging from 0 to 8
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  arr = np.arange(0,9).reshape(3,3)

  return (arr).tolist()

In [170]:
print(create_matrix())

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [171]:
def linear_space():

  ### Create an array of 20 linearly spaced points between 0 and 1
  ### Convert your output into list 
  ### e.g return list(arr) 
  arr = np.linspace(0,1,20)
  return list(arr)

In [173]:
print(linear_space())

[0.0, 0.05263157894736842, 0.10526315789473684, 0.15789473684210525, 0.21052631578947367, 0.2631578947368421, 0.3157894736842105, 0.3684210526315789, 0.42105263157894735, 0.47368421052631576, 0.5263157894736842, 0.5789473684210527, 0.631578947368421, 0.6842105263157894, 0.7368421052631579, 0.7894736842105263, 0.8421052631578947, 0.894736842105263, 0.9473684210526315, 1.0]


In [175]:
def decimal_mat():

  ### Create an array of size 10*10 consisting of numbers from 0.01 to 1
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  arr= np.linspace(0.01,1,100).reshape(10,10)
  return arr.tolist()

In [177]:

print(decimal_mat())

[[0.01, 0.02, 0.03, 0.04, 0.05, 0.060000000000000005, 0.06999999999999999, 0.08, 0.09, 0.09999999999999999], [0.11, 0.12, 0.13, 0.14, 0.15000000000000002, 0.16, 0.17, 0.18000000000000002, 0.19, 0.2], [0.21000000000000002, 0.22, 0.23, 0.24000000000000002, 0.25, 0.26, 0.27, 0.28, 0.29000000000000004, 0.3], [0.31, 0.32, 0.33, 0.34, 0.35000000000000003, 0.36000000000000004, 0.37, 0.38, 0.39, 0.4], [0.41000000000000003, 0.42000000000000004, 0.43, 0.44, 0.45, 0.46, 0.47000000000000003, 0.48000000000000004, 0.49, 0.5], [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.5700000000000001, 0.5800000000000001, 0.59, 0.6], [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.6900000000000001, 0.7000000000000001], [0.7100000000000001, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8], [0.81, 0.8200000000000001, 0.8300000000000001, 0.8400000000000001, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9], [0.91, 0.92, 0.93, 0.9400000000000001, 0.9500000000000001, 0.9600000000000001, 0.97, 0.98, 0.99, 1.0]]


In [185]:
def slices_1():

  # This is a given array
  arr = np.arange(1,26).reshape(5,5)
  # array([[ 1,  2,  3,  4,  5],
  #      [ 6,  7,  8,  9, 10],
  #      [11, 12, 13, 14, 15],
  #      [16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])

  # Write a code to slice this given array
  ### Convert your output into list 
  q = arr[ 2: , 1: ]
  ### e.g return (arr).tolist()
  # array([[12, 13, 14, 15],
  #      [17, 18, 19, 20],
  #      [22, 23, 24, 25]])

  return (q).tolist()

In [186]:
print(slices_1())

[[12, 13, 14, 15], [17, 18, 19, 20], [22, 23, 24, 25]]


In [188]:
def slices_2():

  # This is a given array
  arr = np.arange(1,26).reshape(5,5)
  # array([[ 1,  2,  3,  4,  5],
  #      [ 6,  7,  8,  9, 10],
  #      [11, 12, 13, 14, 15],
  #      [16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])
  r = arr[ :3 , 1:2 ]
  # Write a code to slice this given array
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  # array([[ 2],
  #      [ 7],
  #      [12]])

  return (r).tolist()
  

In [189]:
print(slices_2())

[[2], [7], [12]]


In [191]:
def slices_3():

  # This is a given array
  arr = np.arange(1,26).reshape(5,5)
  # array([[ 1,  2,  3,  4,  5],
  #      [ 6,  7,  8,  9, 10],
  #      [11, 12, 13, 14, 15],
  #      [16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])
  w = arr[ 3: , :5 ]
  # Write a code to slice this given array
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  # array([[16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])

  return (w).tolist()


# Great job!

In [193]:
print(slices_3())

[[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [194]:
# it was fun really enjoyed !! :))