<a href="https://colab.research.google.com/github/nakshatra2003/Python-Workshop/blob/main/PythonMOL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
!pip install numpy

In [49]:
import numpy as np

In [112]:
def power(a,b):
  return a**b

In [113]:
def split_str(s):
  return s.split()

In [11]:
def format(planet,diameter):
  planet="Earth" 
  diameter=12742

#  print("The diameter of {} is {} kilometers.".format(planet,diameter))
  return ('The diameter of {} is {} kilometers.'.format(planet,diameter))

In [114]:
def indexing(lst):
    
# ** Given this nested list, use indexing to grab the word "hello" **

  lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
  return lst[3][1][2][0]

In [115]:
def dictionary(d):
    
# ** Given this nested dictionary grab the word "hello". Be prepared, this will be annoying/tricky **
  d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}


  return d['k1'][3]['tricky'][3]['target'][3]

In [116]:
def subjective():
    
# ** What is the main difference between a tuple and a list? **
# Tuple is ________

    return "immutable"

In [14]:
def domainGet(email):
    
    # ** Create a function that grabs the email website domain from a string in the form:nakshatra **
# 
#     user@domain.com
#     
# **So for example, passing "user@domain.com" would return: domain.com**
    s=email.split('@')[1]
    return s

In [39]:
def findDog(st):
    
# ** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **
    s=set(st.split())
#   print(s)
    for item in s:
#     print(item)
      if(item=="dog"):
        return True

In [46]:
def countDog(st):
  i=0
# ** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **
  p=st.split()
  for item in p:
    if(item=="dog"):
      i=i+1
  return i

In [50]:
def lambdafunc(seq):
    
    # ** Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. For example:**
# 
#     seq = ['soup','dog','salad','cat','great']
# 
# **should be filtered down to:**
# 
#     ['soup','salad']

    return list(filter(lambda item: item[0]=="s",seq))

In [53]:

def caught_speeding(speed, is_birthday):
    
    
# **You are driving a little too fast, and a police officer stops you. Write a function
#   to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
#   If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
#   and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
#   cases. **
  if(speed<61 or (speed<66 and is_birthday)):
    return "No Ticket"
  elif((speed>60 and speed<81) or (speed<86 and is_birthday)):
    return "Small Ticket"
  else:
    return "Big Ticket"

In [68]:
def create_arr_of_fives():
    
  #### Create an array of 10 fives
  #### Convert your output into list 
  #### e.g return list(arr)
  arr = np.ones(10)
  for i in range(10):
    arr[i]= 5*arr[i]
  return list(arr)

In [78]:
def even_num():
    
  ### Create an array of all the even integers from 10 to 50
  ### Convert your output into list 
  ### e.g return list(arr) 
  arr=np.arange(10,51,2)

  return (list(arr))

In [84]:
def create_matrix():
    
  ### Create a 3x3 matrix with values ranging from 0 to 8
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  arr=(np.arange(0,9)).reshape(3,3)

  return (arr).tolist()

In [90]:
def linear_space():
    
  ### Create an array of 20 linearly spaced points between 0 and 1
  ### Convert your output into list 
  ### e.g return list(arr) 
  arr = np.linspace(0,1,20)
  return list(arr)

In [97]:
def decimal_mat():
    
  ### Create an array of size 10*10 consisting of numbers from 0.01 to 1
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  arr = np.linspace(0.01,1,100)
  arr = arr.reshape(10,10)
  return (arr).tolist()

In [106]:
def slices_1():
    
  # This is a given array
  arr = np.arange(1,26).reshape(5,5)
  # array([[ 1,  2,  3,  4,  5],
  #      [ 6,  7,  8,  9, 10],
  #      [11, 12, 13, 14, 15],
  #      [16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])

  # Write a code to slice this given array
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  # array([[12, 13, 14, 15],
  #      [17, 18, 19, 20],
  #      [22, 23, 24, 25]])

  return (arr[2:,1:]).tolist()
               

In [104]:
def slices_2():
    
  # This is a given array
  arr = np.arange(1,26).reshape(5,5)
  # array([[ 1,  2,  3,  4,  5],
  #      [ 6,  7,  8,  9, 10],
  #      [11, 12, 13, 14, 15],
  #      [16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])

  # Write a code to slice this given array
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  # array([[ 2],
  #      [ 7],
  #      [12]])

  return (arr[:3,1]).tolist()

In [110]:
def slices_3():
    
  # This is a given array
  arr = np.arange(1,26).reshape(5,5)
  # array([[ 1,  2,  3,  4,  5],
  #      [ 6,  7,  8,  9, 10],
  #      [11, 12, 13, 14, 15],
  #      [16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])

  # Write a code to slice this given array
  ### Convert your output into list 
  ### e.g return (arr).tolist()
  # array([[16, 17, 18, 19, 20],
  #      [21, 22, 23, 24, 25]])
    
  return (arr[3:,:]).tolist()