# Python walk-through

This notebook will just go through the basic topics in order:


###Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets

###General
    * Comparison Operators
    * if, elif, else Statements
    * for Loops
    * while Loops
    * range()
    * list comprehension
    * functions
    * lambda expressions
    * map and filter
    * methods
    * Error handling


### Numpy
    * Built in methods
    * Attributes
    * Indexing
    * Selection
    * Broadcasting
    * 2D-arrays
    * Slicing
    * Selection
    * Arithmetic operations
    * Universal functions

* Object oriented programming


## Data types

### Numbers

In [ ]:
1 + 1

2

In [ ]:
1 * 3

3

In [ ]:
1 / 2

0.5

In [ ]:
2 ** 4

16

In [ ]:
4 % 2

0

In [ ]:
5 % 2

1

In [ ]:
(2 + 3) * (5 + 5)

50

### Variable Assignment

In [ ]:
# Can not start with number or special characters
name_of_var = 2

In [ ]:
x = 2
y = 3

In [ ]:
z = x + y

In [ ]:
z

5

### Strings

In [ ]:
'single quotes'

'single quotes'

In [1]:
"double quotes"

'double quotes'

In [ ]:
" wrap lot's of other quotes"


" wrap lot's of other quotes"

### Printing

In [3]:
x = 'hello'

In [4]:
x

'hello'

In [5]:
print(x)

hello


In [6]:
num = 12
name = 'Sam'

In [7]:
# print('My number is: {one}, and my name is: {two}'.format(one=num,two=name))
print("{var} this is my number".format(var = num))

12 this is my number


In [ ]:
num = 14
print('My number is: {}, and my name is: {}'.format(num,name))

My number is: 14, and my name is: Sam


### Lists

In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
[ 'hi' , 1 , [1,2] ]

['hi', 1, [1, 2]]

In [ ]:
my_list = ['a','b','c']

In [ ]:
my_list.append('d')

In [ ]:
my_list

['a', 'b', 'c', 'd']

In [ ]:
my_list[0]

'a'

In [ ]:
my_list[1]

'b'

In [ ]:
my_list[ 1 :  ]

['b', 'c', 'd']

In [ ]:
my_list[ : 1]

['a']

In [ ]:
my_list[0] = 'NEW'

In [ ]:
my_list

['NEW', 'b', 'c', 'd']

In [ ]:
nest = [1,2,3,[4,5,['target']]]

In [ ]:
nest[3]

[4, 5, ['target']]

In [ ]:
nest[3][2]

['target']

In [ ]:
nest[3][2][0]

'target'

### Dictionaries

In [8]:
d = { 'key1':'item1' , 'key2':'item2' }

In [9]:
d

{'key1': 'item1', 'key2': 'item2'}

In [10]:
d['key1']

'item1'

In [11]:
# The values in dictionary items can be of any data type
dict_ = {
  "brand": "Ford" ,                    # String
  "electric": False,                  # Boolean
  "year": 1964,                       # Int
  "colors": ["red", "white", "blue"]  # List  
}

In [12]:
dict_

{'brand': 'Ford',
 'electric': False,
 'year': 1964,
 'colors': ['red', 'white', 'blue']}

In [13]:
print(type(dict_["year"]))

<class 'int'>


### Booleans

In [ ]:
True

True

In [ ]:
False

False

### Tuples 

In [15]:
t = (1,2,3)

In [16]:
t[0]

1

In [17]:
t[0] = 'NEW'

TypeError: 'tuple' object does not support item assignment

### Sets

In [18]:
{1,2,3}

{1, 2, 3}

In [ ]:
{1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

{1, 2, 3}

In [19]:
s = set([1,1,1,2,3,3,3,3,3])
s

{1, 2, 3}

In [20]:
s.add(4)
s

{1, 2, 3, 4}

In [21]:
s.add(4)
# It wont add another 4 
s

{1, 2, 3, 4}

## Comparison Operators

In [ ]:
1 > 2

False

In [ ]:
1 < 2

True

In [ ]:
1 >= 1

True

In [ ]:
1 <= 4

True

In [ ]:
1 == 1

True

In [ ]:
# It will give you error
# Coz here you are doing a variable assigment
1 = 1 

SyntaxError: ignored

In [ ]:
'hi' == 'bye'

False

## Logic Operators

In [ ]:
# T and T -> T  # T or T -> T
# T and F -> F  # T or F -> T
# F and T -> F  # F or T -> T
# F and F -> F  # F or F -> F

In [ ]:
(1 > 2) and (2 < 3)

False

In [ ]:
(1 > 2) or (2 < 3)

True

In [ ]:
(1 == 2) or (2 == 3) or (4 == 4)
# F or F 
# F 
# F or T
# T


True

## if,elif, else Statements

In [ ]:
if (1 < 2):
  print('Yep!')

Yep!


In [ ]:
if (1 > 2):
    print('yep!')


In [ ]:
if (1 > 2):
    print('first')
else:
    print('last')

last


In [ ]:
if 1 > 2:
    print('first')
else:
    print('last')

last


In [ ]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
elif 4==3:
  print("four")
else:
    print('Last')


print('DOne')

middle
DOne


## for Loops

In [ ]:
seq = [1,2,3,4,5]

In [ ]:
for item in seq:
    print(item)

1
2
3
4
5


In [ ]:
for item in seq:
    print('Yep')

Yep
Yep
Yep
Yep
Yep


In [ ]:
for jelly in seq:
    print(jelly+jelly)

2
4
6
8
10


## while Loops

In [ ]:
i = 1
while (i <= 5):
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4
i is: 5


## range()

In [ ]:
range(5)

range(0, 5)

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

## list comprehension

In [ ]:
x = [1,2,3,4]

In [ ]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


In [ ]:
store = [item**3 for item in x]
store

[1, 8, 27, 64]

## functions

In [22]:
def my_func(param1='default'):
    """
    Docstring goes here.

    Add numbers 
      
    """
    print(param1)

In [23]:
my_func

<function __main__.my_func(param1='default')>

In [24]:
my_func()

default


In [29]:
my_func("2+6")
my_func(2+6)

2+6
8


In [30]:
my_func(param1='new param')

new param


In [ ]:
def square(x):
    return x**2

In [ ]:
out = square(34)

In [ ]:
print(out)

1156


## lambda expressions

In [ ]:
def times2(var):
    return var*2

In [ ]:
times2(2)

4

In [ ]:
def times2(var):return var*2

In [ ]:
lambda var: var*2

<function __main__.<lambda>>

In [ ]:
func = lambda var: var*3
func(3)

9

In [ ]:
x = lambda a : a + 10
print(x(5))

15


In [ ]:
x = lambda a , b : a * b
print(x(5, 6))

30


## map and filter

In [ ]:
def times2(var):
    return var*2

times2(4)

8

In [ ]:
seq = [1,2,3,4,5]

In [ ]:
# Apply times2 func on each element
map( times2  , seq)
# Returns map at a particular place at memory

In [ ]:
# Returns the list 
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [ ]:
list(map(lambda var: var*3 ,seq))

[3, 6, 9, 12, 15]

In [ ]:
# Filters out or returns boolean value
filter(lambda item: item%2 == 0, seq)

In [ ]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

## methods

In [6]:
st = 'hello mY  name is Sam'

In [8]:
st.lower()

'hello my  name is sam'

In [9]:
st.upper()

'HELLO MY  NAME IS SAM'

In [10]:
st.split()

['hello', 'mY', 'name', 'is', 'Sam']

In [1]:
tweet = 'Go Sports! #Sports'

In [2]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [6]:
tweet.split('#')[1]

'S'

In [ ]:
d 

{'key1': 'item1', 'key2': 'item2'}

In [22]:
d.keys()

NameError: name 'd' is not defined

In [23]:
d.items()

NameError: name 'd' is not defined

In [ ]:
lst = [1,2,3]

In [ ]:
lst.pop()

2

In [24]:
lst.append(5)

NameError: name 'lst' is not defined

In [ ]:
lst

[1, 5]

In [ ]:
'x' in [1,2,3]

False

In [ ]:
'x' in ['x','y','z']

True

# Error Handling

In [31]:
var=10
answer = int(input("Enter Number: "))
var/answer

1.8e-64

In [36]:

# code asks user for number and divides 10 by it
# enter '0' to trigger exception
# enter any string to check for exception
try:
    var=10
    answer = int(input("Enter Number: "))
    var/answer
except ZeroDivisionError as e:
    print(e)
except ValueError:
    print("Caught any exception dont pass a string")

Caught any exception dont pass a string


In [ ]:
try:
    var=10
    answer = int(input("Enter Number: "))
    var/answer
except ZeroDivisionError as e:
    print(e)
except ValueError:
    print("Caught any exception")
except:
    pass

    
finally:
    print("Exit code")


Enter Number: 45
Exit code


# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.



## Install numpy 

In [ ]:
# !pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the workshop. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
ar = np.array(my_list)
ar 


array([1, 2, 3])

In [ ]:
#Convert back array in to list
list(ar)

[1, 2, 3]

In [ ]:
my_matrix = [ [1,2,3] , [4,5,6] , [7,8,9] ]
arr = np.array(my_matrix)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Convert 2d array into list
list(arr)
# It is storing a list of arrays

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
#Converts 2d array to list
arr.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [ ]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(3)

array([ 1.,  1.,  1.])

In [ ]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [ ]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(3)

array([0.45346703, 0.1497983 , 0.87266952])

In [ ]:
np.random.rand(5,5)

array([[0.42442332, 0.2524502 , 0.42153375, 0.42342204, 0.99055167],
       [0.908554  , 0.87508428, 0.19406493, 0.92307498, 0.06234637],
       [0.35323966, 0.05491062, 0.39163486, 0.57011386, 0.36450496],
       [0.34669702, 0.91678722, 0.41248057, 0.37321225, 0.48298827],
       [0.21634103, 0.90925935, 0.46150927, 0.55268504, 0.13477428]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(6)

array([-0.16605779,  0.65824292, -0.35998725,  0.07601771, -0.34089485,
        0.11430547])

In [ ]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)

94

In [ ]:
np.random.randint(1,100,10)

array([40, 77, 38, 92, 50, 22, 89, 12, 88, 92])

In [ ]:
from numpy.random import randint 
randint(1,100,10)

array([24, 70, 33, 67,  4, 90, 68, 63, 68, 96])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([49,  9, 10, 26,  4, 34, 25, 13, 44, 40])

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([49,  9, 10, 26,  4, 34, 25, 13, 44, 40])

In [ ]:
ranarr.max()

49

In [ ]:
# Index of max element
ranarr.argmax()

0

In [ ]:
ranarr.min()

4

In [ ]:
# Index of min element
ranarr.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

# NumPy Indexing and Selection

Now we will discuss how to select elements or groups of elements from an array.

In [ ]:
#Creating sample array
arr = np.arange(0,11)

In [ ]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[ :2 , 1: ]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[ 2 , : ]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. 


## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
import numpy as np
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [ ]:
np.max(arr) #same as arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

# Object Oriented Programming

#### Python is a multi-paradigm programming language. It supports different programming approaches.

One of the popular approaches to solve a programming problem is by creating objects. This is known as Object-Oriented Programming (OOP).

An object has two characteristics:
* attributes
* behavior


#### Let's take an example:
A parrot is an object, as it has the following properties:

name, age, color as attributes singing, dancing as behavior

The concept of OOP in Python focuses on creating reusable code. This concept is also known as DRY (Don't Repeat Yourself).

# Class
A class is a blueprint for the object.

We can think of class as a sketch of a parrot with labels. It contains all the details about the name, colors, size etc. Based on these descriptions, we can study about the parrot. Here, a parrot is an object.

The example for class of parrot can be :

In [ ]:
class Parrot:
    pass


Here, we use the class keyword to define an empty class Parrot. From class, we construct instances. An instance is a specific object created from a particular class.

# Object
An object (instance) is an instantiation of a class. When class is defined, only the description for the object is defined. Therefore, no memory or storage is allocated.

The example for object of parrot class can be:

In [ ]:
obj = Parrot()

Here, obj is an object of class Parrot.

Suppose we have details of parrots. Now, we are going to show how to build the class and objects of parrots.

In [ ]:
# We created a class with the name Parrot. 
class Parrot:

    def check(self):
      print("Check")


    # instance attribute
    def config(self, name, age):
        self.name = name
        self.age = age
        print(name)
        print(age)


#Created a object
obj = Parrot()


# Parrot.check(obj)
# Parrot.config(obj,'Birdy',5)

# We can directly use object
obj.check()
obj.config('Birdy',5)

Check
Birdy
5


##### Instance
We create instances of the Parrot class. Here, blu and woo are references (value) to our new objects

In [ ]:
# We created a class with the name Parrot. 
# Then, we define attributes. The attributes are a characteristic of an object.

class Parrot:

    # instance attribute
    def __init__(self):
        print("Called automatically")

    def check(self):
      print("Check")


    # instance attribute
    def config(self, name, age):
        self.name = name
        self.age = age
        print(name)
        print(age)
    

#  we create instances of the Parrot class. Here, blu and woo are references (value) to our new objects
# instantiate the Parrot class
blu = Parrot()
woo = Parrot()



Called automatically
Called automatically


In [ ]:
class Parrot:

    # Now we are passing variables in our init function
    def __init__(self,color,size):
        self.color = color
        self.size = size
        print("show")

    # instance attribute
    def config(self):
        print("Color is : ",self.color)
        print("Size is : ",self.size)

obj = Parrot('Gnree',4)
obj2 = Parrot('Blue',5)

obj.config()
obj2.config()

show
show
Color is :  Green
Size is :  4
Color is :  Blue
Size is :  5


### Overview

In the above program, we created a class with the name Parrot. 

These attributes are defined inside the init method of the class. It is the initializer method that is first run as soon as the object is created.

Then, we create instances of the Parrot class. Here, blu and woo are references (value) to our new objects.

Similarly, we access the instance attributes using blu.name and blu.age. 

# Great Job!

That's all we need to know for now!

Check out the github link for assignment :
https://github.com/utkarsh-iitbhu/Python-Workshop

For git and github tutorial you can refer too : 
https://youtube.com/playlist?list=PLLt4yMoVgczVgFcTzT60U5IXtNX1qjHL9




## Check out some cool projects in python 

https://github.com/recognai/rubrix

https://github.com/httpie/httpie

https://github.com/ActivityWatch/activitywatch

https://github.com/adamghill/django-unicorn

https://github.com/sherlock-project/sherlock

https://github.com/vinta/awesome-python

https://github.com/Ciphey/Ciphey

https://github.com/encode/django-rest-framework